platform :ios, '9.0'

target 'Venturesity Task' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Venturesity Task

pod 'Firebase/Core'

pod 'Firebase/Database'

end
